# -*- coding: utf-8 -*-
"""Retrieval-based Botipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3p-l89FVHmSzXSR3sveN68ud7smOSiz
"""

!pip install transformers gradio

import pandas as pd

# Replace 'your_file.json' with the path to your JSON file
df = pd.read_json('/content/merged_data.json')

# Display the first few rows
print(df.head())

import pandas as pd
import gradio as gr
import json

# Read the JSON dataset into a DataFrame
# Replace 'qa_dataset.json' with the path to your JSON file
with open('merged_data.json', 'r') as file:
    data = json.load(file)

# If data is a list of dicts, load directly
df = pd.DataFrame(data)

# Alternatively, if data is nested, use json_normalize
# df = pd.json_normalize(data)

# Inspect the DataFrame
print(df.head())

# Function to find the answer from DataFrame
def get_answer(user_input):
    user_input_lower = user_input.lower()
    for idx, row in df.iterrows():
        question_lower = row['question'].lower()
        if question_lower in user_input_lower:
            return row['answer']
    return "Sorry, I don't have an answer for that question right now!"

# Gradio interface
iface = gr.Interface(
    fn=get_answer,
    inputs=gr.Textbox(lines=2, placeholder="Ask about..."),
    outputs="text",
    title="Predefined Q&A Chatbot",

)

iface.launch()